#pragma once

#include "../MinDef.h"

EXTERN_C_START

#pragma region Unique ID

_Kernel_entry_
NTSYSCALLAPI
NTSTATUS
NTAPI
NtAllocateLocallyUniqueId(
    _Out_ PLUID Luid);

_Kernel_entry_
NTSYSCALLAPI
NTSTATUS
NTAPI
NtSetUuidSeed(
    _In_ PCHAR Seed);

_Kernel_entry_
NTSYSCALLAPI
NTSTATUS
NTAPI
NtAllocateUuids(
    _Out_ PULARGE_INTEGER Time,
    _Out_ PULONG Range,
    _Out_ PULONG Sequence,
    _Out_ PCHAR Seed);

#pragma endregion

#pragma region Hard Error

/**
 * The HARDERROR_RESPONSE_OPTION enumeration specifies the type of user
 * interface prompt that may be displayed when a hard error occurs.
 */
typedef enum _HARDERROR_RESPONSE_OPTION
{
    OptionAbortRetryIgnore,
    OptionOk,
    OptionOkCancel,
    OptionRetryCancel,
    OptionYesNo,
    OptionYesNoCancel,
    OptionShutdownSystem,
    OptionOkNoWait,
    OptionCancelTryContinue
} HARDERROR_RESPONSE_OPTION;

/**
 * The HARDERROR_RESPONSE enumeration specifies the response returned by the
 * caller or user when handling a hard error condition.
 */
typedef enum _HARDERROR_RESPONSE
{
    ResponseReturnToCaller,
    ResponseNotHandled,
    ResponseAbort,
    ResponseCancel,
    ResponseIgnore,
    ResponseNo,
    ResponseOk,
    ResponseRetry,
    ResponseYes,
    ResponseTryAgain,
    ResponseContinue
} HARDERROR_RESPONSE;

/**
 * HARDERROR_OVERRIDE_ERRORMODE indicates that the system should ignore the
 * calling process's error mode when processing a hard error.
 */
#define HARDERROR_OVERRIDE_ERRORMODE 0x10000000

/**
 * The NtRaiseHardError routine raises a hard error or serious error dialog box being displayed to the user.
 *
 * \param[in] ErrorStatus The NTSTATUS code that describes the error condition.
 * \param[in] NumberOfParameters The number of parameters in the Parameters array.
 * \param[in] UnicodeStringParameterMask A bitmask indicating which entries in the Parameters array are Unicode strings.
 * \param[in] Parameters An array of parameters to be used in the error message.
 * \param[in] ValidResponseOptions Specifies the valid responses that the user can select in the error dialog.
 * \param[out] Response Receives the user's response to the error dialog.
 * \return NTSTATUS Successful or errant status.
 */
_Analysis_noreturn_
DECLSPEC_NORETURN
_Kernel_entry_
NTSYSCALLAPI
NTSTATUS
NTAPI
NtRaiseHardError(
    _In_ NTSTATUS ErrorStatus,
    _In_ ULONG NumberOfParameters,
    _In_ ULONG UnicodeStringParameterMask,
    _In_reads_(NumberOfParameters) PULONG_PTR Parameters,
    _In_ ULONG ValidResponseOptions,
    _Out_ PULONG Response);

/**
 * The NtSetDefaultHardErrorPort routine sets the system's default hard error
 * port, which is used by the kernel to deliver hard error notifications to a
 * user-mode process.
 *
 * \param DefaultHardErrorPort A handle to a port object that will receive
 * hard error messages generated by the system.
 * \return NTSTATUS Successful or errant status.
 */
_Kernel_entry_
NTSYSCALLAPI
NTSTATUS
NTAPI
NtSetDefaultHardErrorPort(
    _In_ HANDLE DefaultHardErrorPort);

#pragma endregion

#pragma region Global Flags

// Global flags (NtGlobalFlag)
//
// \see https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-flag-table

#define FLG_STOP_ON_EXCEPTION 0x00000001            // Stop on exception (R,K,I)
#define FLG_SHOW_LDR_SNAPS 0x00000002               // Show loader snaps (R,K,I)
#define FLG_DEBUG_INITIAL_COMMAND 0x00000004        // Debug initial command (R)
#define FLG_STOP_ON_HUNG_GUI 0x00000008             // Stop on hung GUI (K)
#define FLG_HEAP_ENABLE_TAIL_CHECK 0x00000010       // Enable heap tail checking (R,K,I)
#define FLG_HEAP_ENABLE_FREE_CHECK 0x00000020       // Enable heap free checking (R,K,I)
#define FLG_HEAP_VALIDATE_PARAMETERS 0x00000040     // Enable heap parameter checking (R,K,I)
#define FLG_HEAP_VALIDATE_ALL 0x00000080            // Enable heap validation on call (R,K,I)
#define FLG_APPLICATION_VERIFIER 0x00000100         // Enable application verifier (R,K,I)
#define FLG_MONITOR_SILENT_PROCESS_EXIT 0x00000200  // Enable silent process exit monitoring (R)
#define FLG_POOL_ENABLE_TAGGING 0x00000400          // Enable pool tagging (R)
#define FLG_HEAP_ENABLE_TAGGING 0x00000800          // Enable heap tagging (R,K,I)
#define FLG_USER_STACK_TRACE_DB 0x00001000          // Create user mode stack trace database (R,K,I)
#define FLG_KERNEL_STACK_TRACE_DB 0x00002000        // Create kernel mode stack trace database (R)
#define FLG_MAINTAIN_OBJECT_TYPELIST 0x00004000     // Maintain a list of objects for each type (R)
#define FLG_HEAP_ENABLE_TAG_BY_DLL 0x00008000       // Enable heap tagging by DLL (R,K,I)
#define FLG_DISABLE_STACK_EXTENSION 0x00010000      // Disable stack extension (I)
#define FLG_ENABLE_CSRDEBUG 0x00020000              // Enable debugging of Win32 subsystem (R)
#define FLG_ENABLE_KDEBUG_SYMBOL_LOAD 0x00040000    // Enable loading of kernel debugger symbols (R,K)
#define FLG_DISABLE_PAGE_KERNEL_STACKS 0x00080000   // Disable paging of kernel stacks (R)
#define FLG_ENABLE_SYSTEM_CRIT_BREAKS 0x00100000    // Enable system critical breaks (R,K,I)
#define FLG_HEAP_DISABLE_COALESCING 0x00200000      // Disable heap coalesce on free (R,K,I)
#define FLG_ENABLE_CLOSE_EXCEPTIONS 0x00400000      // Enable close exception (R,K)
#define FLG_ENABLE_EXCEPTION_LOGGING 0x00800000     // Enable exception logging (R,K)
#define FLG_ENABLE_HANDLE_TYPE_TAGGING 0x01000000   // Enable object handle type tagging (R,K)
#define FLG_HEAP_PAGE_ALLOCS 0x02000000             // Enable page heap (R,K,I)
#define FLG_DEBUG_INITIAL_COMMAND_EX 0x04000000     // Debug WinLogon (R)
#define FLG_DISABLE_DBGPRINT 0x08000000             // Buffer DbgPrint Output (R,K)
#define FLG_CRITSEC_EVENT_CREATION 0x10000000       // Early critical section event creation (R,K,I)
#define FLG_STOP_ON_UNHANDLED_EXCEPTION 0x20000000  // Stop on unhandled user-mode exception (R,K,I)
#define FLG_LDR_TOP_DOWN 0x20000000                 // Load image using large pages if possible (I)
#define FLG_ENABLE_HANDLE_EXCEPTIONS 0x40000000     // Enable bad handles detection (R,K)
#define FLG_DISABLE_PROTDLLS 0x80000000             // Disable protected DLL verification (R,K,I)
#define FLG_VALID_BITS 0xffffffff

#define FLG_USERMODE_VALID_BITS (FLG_STOP_ON_EXCEPTION | \
    FLG_SHOW_LDR_SNAPS | \
    FLG_HEAP_ENABLE_TAIL_CHECK | \
    FLG_HEAP_ENABLE_FREE_CHECK | \
    FLG_HEAP_VALIDATE_PARAMETERS | \
    FLG_HEAP_VALIDATE_ALL | \
    FLG_APPLICATION_VERIFIER | \
    FLG_MONITOR_SILENT_PROCESS_EXIT | \
    FLG_HEAP_ENABLE_TAGGING | \
    FLG_USER_STACK_TRACE_DB | \
    FLG_HEAP_ENABLE_TAG_BY_DLL | \
    FLG_DISABLE_STACK_EXTENSION | \
    FLG_ENABLE_SYSTEM_CRIT_BREAKS | \
    FLG_HEAP_DISABLE_COALESCING | \
    FLG_DISABLE_PROTDLLS | \
    FLG_HEAP_PAGE_ALLOCS | \
    FLG_CRITSEC_EVENT_CREATION | \
    FLG_STOP_ON_UNHANDLED_EXCEPTION | \
    FLG_LDR_TOP_DOWN)

#define FLG_BOOTONLY_VALID_BITS (FLG_KERNEL_STACK_TRACE_DB | \
    FLG_MAINTAIN_OBJECT_TYPELIST | \
    FLG_ENABLE_CSRDEBUG | \
    FLG_DEBUG_INITIAL_COMMAND | \
    FLG_DEBUG_INITIAL_COMMAND_EX | \
    FLG_DISABLE_PAGE_KERNEL_STACKS)

#define FLG_KERNELMODE_VALID_BITS (FLG_STOP_ON_EXCEPTION | \
    FLG_SHOW_LDR_SNAPS | \
    FLG_STOP_ON_HUNG_GUI | \
    FLG_POOL_ENABLE_TAGGING | \
    FLG_ENABLE_KDEBUG_SYMBOL_LOAD | \
    FLG_ENABLE_CLOSE_EXCEPTIONS | \
    FLG_ENABLE_EXCEPTION_LOGGING | \
    FLG_ENABLE_HANDLE_TYPE_TAGGING | \
    FLG_DISABLE_DBGPRINT | \
    FLG_ENABLE_HANDLE_EXCEPTIONS)

#pragma endregion

/**
 * MAX_WOW64_SHARED_ENTRIES defines the number of shared entries available to
 * the WOW64 (Windows-on-Windows 64-bit) subsystem.
 */
#define MAX_WOW64_SHARED_ENTRIES 16

/**
 * The NtUmsThreadYield routine yields control to the user-mode scheduling (UMS) scheduler thread on which the calling UMS worker thread is running.
 * Note: As of Windows 11, user-mode scheduling is not supported. All calls fail with the error STATUS_NOT_SUPPORTED.
 *
 * \param SchedulerParam Optional handle to the keyed event object. If NULL, the default keyed event is used.
 * \return NTSTATUS Successful or errant status.
 * \sa https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-umsthreadyield
 */
_Kernel_entry_
NTSYSCALLAPI
NTSTATUS
NTAPI
NtUmsThreadYield(
    _In_ PVOID SchedulerParam);

EXTERN_C_END
