#pragma once

// IMsTscAxEvents DISPIDs:
// https://learn.microsoft.com/en-us/windows/win32/termserv/imstscaxevents-interface
#define MSTSCAXEVENT_DISPID_CONNECTING 1
#define MSTSCAXEVENT_DISPID_CONNECTED 2
#define MSTSCAXEVENT_DISPID_LOGINCOMPLETE 3
#define MSTSCAXEVENT_DISPID_DISCONNECTED 4
#define MSTSCAXEVENT_DISPID_ENTERFULLSCREENMODE 5
#define MSTSCAXEVENT_DISPID_LEAVEFULLSCREENMODE 6
#define MSTSCAXEVENT_DISPID_CHANNELRECEIVEDDATA 7
#define MSTSCAXEVENT_DISPID_REQUESTGOFULLSCREEN 8
#define MSTSCAXEVENT_DISPID_REQUESTLEAVEFULLSCREEN 9
#define MSTSCAXEVENT_DISPID_FATALERROR 10
#define MSTSCAXEVENT_DISPID_WARNING 11
#define MSTSCAXEVENT_DISPID_REMOTEDESKTOPSIZECHANGE 12
#define MSTSCAXEVENT_DISPID_IDLETIMEOUTNOTIFICATION 13
#define MSTSCAXEVENT_DISPID_REQUESTCONTAINERMINIMIZE 14
#define MSTSCAXEVENT_DISPID_CONFIRMCLOSE 15
#define MSTSCAXEVENT_DISPID_RECEIVEDTSPUBLICKEY 16
#define MSTSCAXEVENT_DISPID_AUTORECONNECTING 17
#define MSTSCAXEVENT_DISPID_INTERNALDIALOGDISPLAYED 18
#define MSTSCAXEVENT_DISPID_INTERNALDIALOGDISMISSED 19
#define MSTSCAXEVENT_DISPID_ONREMOTEPROGRAMRESULT 20
#define MSTSCAXEVENT_DISPID_ONREMOTEPROGRAMDISPLAYED 21
#define MSTSCAXEVENT_DISPID_LOGONERROR 22
#define MSTSCAXEVENT_DISPID_FOCUSRELEASED 23
#define MSTSCAXEVENT_DISPID_USERNAMEACQUIRED 24
#define MSTSCAXEVENT_DISPID_MOUSEINPUTMODECHANGED 26
#define MSTSCAXEVENT_DISPID_ONSTATUSINFO 27
#define MSTSCAXEVENT_DISPID_SERVICEMESSAGERECEIVED 28
#define MSTSCAXEVENT_DISPID_ONREMOTEWINDOWDISPLAYED 29
#define MSTSCAXEVENT_DISPID_CONNECTIONBARPULLDOWN 30
#define MSTSCAXEVENT_DISPID_ONNETWORKSTATUSCHANGED 32
#define MSTSCAXEVENT_DISPID_AUTORECONNECTED 33
#define MSTSCAXEVENT_DISPID_AUTORECONNECTING2 34
#define MSTSCAXEVENT_DISPID_CONNECTIONBARDEVICES 35
#define MSTSCAXEVENT_DISPID_HVSINOTIFICATION 36
#define MSTSCAXEVENT_DISPID_ONWOKEUPANDRECONNECTING 37
#define MSTSCAXEVENT_DISPID_ONLOCATIONREDIRECTIONENABLEDRECEIVED 39

// OnDisconnected: basic disconnect reasons (distinct from ExtendedDisconnectReasonCode).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imstscaxevents-ondisconnected
#define MSTSCAX_DISCONNECT_REASON_AT_CLIENT_WINSOCK_FDCLOSE 2308L
#define MSTSCAX_DISCONNECT_REASON_BY_SERVER 3L
#define MSTSCAX_DISCONNECT_REASON_CLIENT_DECOMPRESSION_ERROR 3080L
#define MSTSCAX_DISCONNECT_REASON_CONNECTION_TIMED_OUT 264L
#define MSTSCAX_DISCONNECT_REASON_DECRYPTION_ERROR 3078L
#define MSTSCAX_DISCONNECT_REASON_DNS_LOOKUP_FAILED 260L
#define MSTSCAX_DISCONNECT_REASON_DNS_LOOKUP_FAILED2 1288L
#define MSTSCAX_DISCONNECT_REASON_ENCRYPTION_ERROR 2822L
#define MSTSCAX_DISCONNECT_REASON_GET_HOST_BY_NAME_FAILED 1540L
#define MSTSCAX_DISCONNECT_REASON_HOST_NOT_FOUND 520L
#define MSTSCAX_DISCONNECT_REASON_INTERNAL_ERROR 1032L
#define MSTSCAX_DISCONNECT_REASON_INTERNAL_SECURITY_ERROR 2310L
#define MSTSCAX_DISCONNECT_REASON_INTERNAL_SECURITY_ERROR2 2566L
#define MSTSCAX_DISCONNECT_REASON_INVALID_ENCRYPTION 1286L
#define MSTSCAX_DISCONNECT_REASON_INVALID_IP 2052L
#define MSTSCAX_DISCONNECT_REASON_INVALID_SERVER_SECURITY_INFO 1542L
#define MSTSCAX_DISCONNECT_REASON_INVALID_SECURITY_DATA 1030L
#define MSTSCAX_DISCONNECT_REASON_INVALID_IP_ADDR 776L
#define MSTSCAX_DISCONNECT_REASON_LICENSING_FAILED 2056L
#define MSTSCAX_DISCONNECT_REASON_LICENSING_TIMEOUT 2312L
#define MSTSCAX_DISCONNECT_REASON_LOCAL_NOT_ERROR 1L
#define MSTSCAX_DISCONNECT_REASON_NO_INFO 0L
#define MSTSCAX_DISCONNECT_REASON_OUT_OF_MEMORY 262L
#define MSTSCAX_DISCONNECT_REASON_OUT_OF_MEMORY2 518L
#define MSTSCAX_DISCONNECT_REASON_OUT_OF_MEMORY3 774L
#define MSTSCAX_DISCONNECT_REASON_REMOTE_BY_USER 2L
#define MSTSCAX_DISCONNECT_REASON_SERVER_CERTIFICATE_UNPACK_ERR 1798L
#define MSTSCAX_DISCONNECT_REASON_SOCKET_CONNECT_FAILED 516L
#define MSTSCAX_DISCONNECT_REASON_SOCKET_RECV_FAILED 1028L
#define MSTSCAX_DISCONNECT_REASON_TIMEOUT_OCCURRED 1796L
#define MSTSCAX_DISCONNECT_REASON_TIMER_ERROR 1544L
#define MSTSCAX_DISCONNECT_REASON_WINSOCK_SEND_FAILED 772L

// OnDisconnected: authentication and certificate errors.
// https://learn.microsoft.com/en-us/windows/win32/termserv/imstscaxevents-ondisconnected
#define MSTSCAX_SSL_ERR_ACCOUNT_DISABLED 2823L
#define MSTSCAX_SSL_ERR_ACCOUNT_EXPIRED 3591L
#define MSTSCAX_SSL_ERR_ACCOUNT_LOCKED_OUT 3335L
#define MSTSCAX_SSL_ERR_ACCOUNT_RESTRICTION 3079L
#define MSTSCAX_SSL_ERR_CERT_EXPIRED 6919L
#define MSTSCAX_SSL_ERR_DELEGATION_POLICY 5639L
#define MSTSCAX_SSL_ERR_FRESH_CRED_REQUIRED_BY_SERVER 8455L
#define MSTSCAX_SSL_ERR_LOGON_FAILURE 2055L
#define MSTSCAX_SSL_ERR_NO_AUTHENTICATING_AUTHORITY 6151L
#define MSTSCAX_SSL_ERR_NO_SUCH_USER 2567L
#define MSTSCAX_SSL_ERR_PASSWORD_EXPIRED 3847L
#define MSTSCAX_SSL_ERR_PASSWORD_MUST_CHANGE 4615L
#define MSTSCAX_SSL_ERR_POLICY_NTLM_ONLY 5895L
#define MSTSCAX_SSL_ERR_SMARTCARD_CARD_BLOCKED 8711L
#define MSTSCAX_SSL_ERR_SMARTCARD_WRONG_PIN 7175L

// OnLogonError: logon errors and notifications.
// https://learn.microsoft.com/en-us/windows/win32/termserv/imstscaxevents-onlogonerror
// These are not HRESULTs: zero is an error, and negative values can describe logon progress.
#define MSTSCAX_ARBITRATION_CODE_BUMP_OPTIONS (-5L) // Session contention dialog.
#define MSTSCAX_ARBITRATION_CODE_CONTINUE_LOGON (-2L) // Logon continues.
#define MSTSCAX_ARBITRATION_CODE_CONTINUE_TERMINATE (-3L) // Winlogon terminates silently.
#define MSTSCAX_ARBITRATION_CODE_NOPERM_DIALOG (-6L) // No-permissions dialog.
#define MSTSCAX_ARBITRATION_CODE_REFUSED_DIALOG (-7L) // Disconnect-refused dialog.
#define MSTSCAX_ARBITRATION_CODE_RECONN_OPTIONS (-4L) // Reconnect dialog.
#define MSTSCAX_ERROR_CODE_ACCESS_DENIED (-1L) // Access denied.
#define MSTSCAX_LOGON_FAILED_BAD_PASSWORD 0L // Invalid credentials.
#define MSTSCAX_LOGON_FAILED_OTHER 2L // Other logon failure.
#define MSTSCAX_LOGON_FAILED_UPDATE_PASSWORD 1L // Password update required.
#define MSTSCAX_LOGON_WARNING 3L // Informational logon dialog.

// OnFatalError (NDK names for documented numeric values).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imstscaxevents-onfatalerror
#define MSTSCAX_FATAL_ERROR_UNKNOWN 0L
#define MSTSCAX_FATAL_ERROR_INTERNAL_1 1L
#define MSTSCAX_FATAL_ERROR_OUT_OF_MEMORY 2L
#define MSTSCAX_FATAL_ERROR_WINDOW_CREATION 3L
#define MSTSCAX_FATAL_ERROR_INTERNAL_2 4L
#define MSTSCAX_FATAL_ERROR_INVALID_STATE 5L // Internal error 3.
#define MSTSCAX_FATAL_ERROR_INTERNAL_4 6L
#define MSTSCAX_FATAL_ERROR_CONNECTION 7L
#define MSTSCAX_FATAL_ERROR_WINSOCK_INITIALIZATION 100L

// OnWarning (NDK name for the documented numeric value).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imstscaxevents-onwarning
#define MSTSCAX_WARNING_BITMAP_CACHE_CORRUPT 1L

// GatewayUsageMethod.
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclienttransportsettings-gatewayusagemethod
#define MSTSCAX_PROXY_MODE_NONE_DIRECT 0UL
#define MSTSCAX_PROXY_MODE_DIRECT 1UL
#define MSTSCAX_PROXY_MODE_DETECT 2UL
#define MSTSCAX_PROXY_MODE_DEFAULT 3UL
#define MSTSCAX_PROXY_MODE_NONE_DETECT 4UL

// GatewayProfileUsageMethod.
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclienttransportsettings-gatewayprofileusagemethod
#define MSTSCAX_PROXY_PROFILE_MODE_DEFAULT 0UL
#define MSTSCAX_PROXY_PROFILE_MODE_EXPLICIT 1UL

// GatewayCredsSource.
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclienttransportsettings-gatewaycredssource
#define MSTSCAX_PROXY_CREDS_MODE_USERPASS 0UL
#define MSTSCAX_PROXY_CREDS_MODE_SMARTCARD 1UL
#define MSTSCAX_PROXY_CREDS_MODE_ANY 4UL

// AudioRedirectionMode.
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings5-audioredirectionmode
#define MSTSCAX_AUDIO_MODE_REDIRECT 0UL
#define MSTSCAX_AUDIO_MODE_PLAY_ON_SERVER 1UL
#define MSTSCAX_AUDIO_MODE_NONE 2UL

// NetworkConnectionType.
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings7-networkconnectiontype
#define MSTSCAX_CONNECTION_TYPE_MODEM 1UL
#define MSTSCAX_CONNECTION_TYPE_BROADBAND_LOW 2UL
#define MSTSCAX_CONNECTION_TYPE_SATELLITE 3UL
#define MSTSCAX_CONNECTION_TYPE_BROADBAND_HIGH 4UL
#define MSTSCAX_CONNECTION_TYPE_WAN 5UL
#define MSTSCAX_CONNECTION_TYPE_LAN 6UL

// AuthenticationLevel (NDK names for documented numeric values).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings4-authenticationlevel
#define MSTSCAX_AUTHENTICATION_LEVEL_NONE 0UL // Do not authenticate the server.
#define MSTSCAX_AUTHENTICATION_LEVEL_REQUIRED 1UL // Require successful server authentication.
#define MSTSCAX_AUTHENTICATION_LEVEL_PROMPT 2UL // Prompt the user if server authentication fails.

// AuthenticationType (NDK names for documented numeric values).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings6-authenticationtype
#define MSTSCAX_AUTHENTICATION_TYPE_NONE 0UL
#define MSTSCAX_AUTHENTICATION_TYPE_CERTIFICATE 1UL
#define MSTSCAX_AUTHENTICATION_TYPE_KERBEROS 2UL
#define MSTSCAX_AUTHENTICATION_TYPE_CERTIFICATE_AND_KERBEROS 3UL

// KeyboardHookMode (NDK names for documented numeric values).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclientsecuredsettings-keyboardhookmode
#define MSTSCAX_KEYBOARD_HOOK_MODE_LOCAL 0L
#define MSTSCAX_KEYBOARD_HOOK_MODE_REMOTE 1L
#define MSTSCAX_KEYBOARD_HOOK_MODE_FULLSCREEN 2L // Redirect shortcuts only in full-screen mode.

// AudioQualityMode (NDK names for documented numeric values).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings7-audioqualitymode
#define MSTSCAX_AUDIO_QUALITY_DYNAMIC 0UL
#define MSTSCAX_AUDIO_QUALITY_MEDIUM 1UL
#define MSTSCAX_AUDIO_QUALITY_HIGH 2UL

// VideoPlaybackMode (NDK names for documented numeric values).
// https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings7-videoplaybackmode
#define MSTSCAX_VIDEO_PLAYBACK_MODE_DISABLED 0UL
#define MSTSCAX_VIDEO_PLAYBACK_MODE_DEFAULT 1UL // Video redirection follows AudioRedirectionMode.

// MS-RDPEDISP display dimensions (NDK limit names) and orientation in degrees.
// https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpedisp/ea2de591-9203-42cd-9908-be7a55237d1c
// Desktop width must be even. Physical dimensions outside these limits are ignored by the protocol.
#define MSTSCAX_MIN_DESKTOP_SIZE 200L
#define MSTSCAX_MAX_DESKTOP_SIZE 8192L
#define MSTSCAX_MIN_PHYSICAL_SIZE_MM 10L
#define MSTSCAX_MAX_PHYSICAL_SIZE_MM 10000L
#define MSTSCAX_ORIENTATION_LANDSCAPE 0UL
#define MSTSCAX_ORIENTATION_PORTRAIT 90UL
#define MSTSCAX_ORIENTATION_LANDSCAPE_FLIPPED 180UL
#define MSTSCAX_ORIENTATION_PORTRAIT_FLIPPED 270UL
