#pragma once

#include "../MinDef.h"

EXTERN_C_START

/* phnt patches */

DECLARE_HANDLE(BRUSHOBJ);
DECLARE_HANDLE(SURFOBJ);
DECLARE_HANDLE(CLIPOBJ);
DECLARE_HANDLE(XLATEOBJ);
DECLARE_HANDLE(PATHOBJ);
DECLARE_HANDLE(XFORMOBJ);
DECLARE_HANDLE(BLENDOBJ);
DECLARE_HANDLE(STROBJ);

DECLARE_HANDLE(FONTOBJ);
DECLARE_HANDLE(HSURF);
DECLARE_HANDLE(HDEV);
DECLARE_HANDLE(HGLYPH);
DECLARE_HANDLE(UNIVERSAL_FONT_ID);
DECLARE_HANDLE(KERNEL_PVOID);
DECLARE_HANDLE(ARCTYPE);
DECLARE_HANDLE(TMDIFF);
DECLARE_HANDLE(DHSURF);

typedef struct _WIDTHDATA WIDTHDATA, *PWIDTHDATA;
typedef struct _FONT_FILE_INFO FONT_FILE_INFO, *PFONT_FILE_INFO;
typedef struct _EXTTEXTMETRIC EXTTEXTMETRIC, *PEXTTEXTMETRIC;
typedef struct _PERBANDINFO PERBANDINFO, *PPERBANDINFO;
typedef struct _TMW_INTERNAL TMW_INTERNAL, *PTMW_INTERNAL;
typedef ULONG LFTYPE;
typedef ULONG ROP4;
typedef ULONG MIX;
typedef struct _POINTFIX POINTFIX, *PPOINTFIX;
typedef struct _LINEATTRS LINEATTRS, *PLINEATTRS;
typedef struct _XFORML XFORML, *PXFORML;
typedef struct _FONTINFO FONTINFO, *PFONTINFO;
typedef struct _POINTQF POINTQF, *PPOINTQF;
typedef struct _PATHDATA PATHDATA, *PPATHDATA;
typedef struct _CLIPLINE CLIPLINE, *PCLIPLINE;
typedef struct _IFIMETRICS IFIMETRICS, *PIFIMETRICS;
typedef struct _FD_GLYPHSET FD_GLYPHSET, *PFD_GLYPHSET;
typedef struct _FD_GLYPHATTR FD_GLYPHATTR, *PFD_GLYPHATTR;
typedef struct _DPI_INFORMATION DPI_INFORMATION, *PDPI_INFORMATION;
typedef struct _CHWIDTHINFO *PCHWIDTHINFO;
typedef struct _DEVCAPS *PDEVCAPS;
typedef struct _FONT_REALIZATION_INFO2 *PFONT_REALIZATION_INFO2;
typedef struct _GLYPHPOS *PGLYPHPOS;
typedef struct _RECTFX *PRECTFX;
typedef struct _POLYPATBLT *PPOLYPATBLT;
typedef PVOID DHPDEV;
typedef ULONG HLSURF_INFORMATION_CLASS;

typedef UNIVERSAL_FONT_ID* PUNIVERSAL_FONT_ID;

/* FIXME: Unknow types, do not use */

typedef struct
{
    ULONG Unknown;
} HLSURF_INFORMATION_SURFACE, HLSURF_INFORMATION_PRESENTFLAGS, HLSURF_INFORMATION_TOKENUPDATEID, HLSURF_INFORMATION_SET_SIGNALING, DWMSURFACEDATA, HLSURF_INFORMATION_DIRTYREGIONS, HLSURF_INFORMATION_REDIRSTYLE, HLSURF_INFORMATION_SET_GERNERATE_MOVE_DATA;

#include <ntgdi.h>

EXTERN_C_END
